language: node_js
sudo: false
node_js:
  - '14'
install:
  - yarn
cache:
  directories:
    - node_modules
script: 
  - yarn build
  - yarn test:unit
after_success:
  - codecov -f tests/unit/coverage/*.json
