language: node_js
matrix:
  include:
    - dist: bionic
    - dist: xenial
node_js:
  - '14'
install:
  - yarn
cache:
  directories:
    - node_modules
script: 
  - yarn build
  - yarn test:unit
after_success:
  - codecov -f tests/unit/coverage/*.json
