language: node_js
sudo: false
node_js:
  - '14'
install:
  - npm install
cache:
  directories:
    - node_modules
script: 
  - npm run build
  - npm run test:unit
after_success:
  - codecov -f tests/unit/coverage/*.json
